# Generated by Django 3.2.9 on 2021-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myshop",
            name="about_content",
        ),
        migrations.RemoveField(
            model_name="myshop",
            name="seller_info",
        ),
        migrations.RemoveField(
            model_name="myshop",
            name="why_us",
        ),
        migrations.AddField(
            model_name="myshop",
            name="banner_description1",
            field=models.CharField(
                default=1, max_length=50, verbose_name="توضیحات بنر اول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="banner_description2",
            field=models.CharField(
                default=1, max_length=50, verbose_name="توضیحات بنر دوم"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="banner_description3",
            field=models.CharField(
                default=1, max_length=50, verbose_name="توضیحات بنر سوم"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="banner_title1",
            field=models.CharField(
                default=1, max_length=50, verbose_name="عنوان بنر اول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="banner_title2",
            field=models.CharField(
                default=1, max_length=50, verbose_name="عنوان بنر دوم"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="banner_title3",
            field=models.CharField(
                default=1, max_length=50, verbose_name="عنوان بنر سوم"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="description_look",
            field=models.TextField(default=1, verbose_name="توضیحات پوستر"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="image_look",
            field=models.ImageField(
                default=1, upload_to="shops.look", verbose_name="عکس پوستر"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="image_product1",
            field=models.ImageField(
                default=1, upload_to="shops.product", verbose_name="عکس محصول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="image_product2",
            field=models.ImageField(
                default=1, upload_to="shops.product", verbose_name="عکس محصول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="image_product3",
            field=models.ImageField(
                default=1, upload_to="shops.product", verbose_name="عکس محصول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="image_product4",
            field=models.ImageField(
                default=1, upload_to="shops.product", verbose_name="عکس محصول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="image_product5",
            field=models.ImageField(
                default=1, upload_to="shops.product", verbose_name="عکس محصول"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="title_look",
            field=models.CharField(
                default=1, max_length=50, verbose_name="عنوان پوستر"
            ),
            preserve_default=False,
        ),
    ]
