# Generated by Django 3.2.9 on 2021-11-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211119_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shop',
        ),
    ]
