# Generated by Django 3.2.9 on 2021-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment_shop_contact_with_us_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
