# Generated by Django 3.2.9 on 2021-11-19 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_customuser_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myshop",
            name="banner_description1",
        ),
        migrations.RemoveField(
            model_name="myshop",
            name="banner_description2",
        ),
        migrations.RemoveField(
            model_name="myshop",
            name="banner_description3",
        ),
    ]
