# Generated by Django 3.2.6 on 2021-11-21 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_myshop_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="اسم دسته")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="products_category", verbose_name="عکس دسته"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="pakage_shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("price", models.CharField(max_length=10)),
                ("left", models.BooleanField(default=False)),
                ("color", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کالا")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="products", verbose_name="عکس اول کالا"
                    ),
                ),
                (
                    "photo_2",
                    models.ImageField(
                        upload_to="products", verbose_name="عکس دوم کالا"
                    ),
                ),
                (
                    "photo_3",
                    models.ImageField(
                        blank=True, upload_to="products", verbose_name="عکس سوم کالا"
                    ),
                ),
                (
                    "photo_4",
                    models.ImageField(
                        blank=True, upload_to="products", verbose_name="عکس چهارم کالا"
                    ),
                ),
                (
                    "photo_5",
                    models.ImageField(
                        blank=True, upload_to="products", verbose_name="عکس پنجم کالا"
                    ),
                ),
                (
                    "photo_6",
                    models.ImageField(
                        blank=True, upload_to="products", verbose_name="عکس ششم کالا"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="قیمت کالا| بدون تخفیف")),
                (
                    "last_price",
                    models.IntegerField(verbose_name="قیمت نهایی کالا با تخفیف"),
                ),
                ("off", models.PositiveIntegerField(verbose_name="تخفیف")),
                ("details", models.TextField(verbose_name="درباره ی کالا")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان ساخت کالا"
                    ),
                ),
                (
                    "hot",
                    models.BooleanField(default=False, verbose_name="کالا داغ است؟"),
                ),
                (
                    "most_off",
                    models.BooleanField(
                        default=False, verbose_name="کالا پر تخفیف است؟"
                    ),
                ),
                (
                    "rare",
                    models.BooleanField(
                        default=False, verbose_name="کالا بسیار ویژه است؟"
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="کالا موجود است؟"),
                ),
                ("star_rate", models.PositiveIntegerField(blank=True, default=0)),
                ("stars", models.CharField(default=0, max_length=5)),
                ("stars_left", models.CharField(blank=True, max_length=5)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.category",
                        verbose_name="دسته ی کالا",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="myshop",
            name="seller_info",
            field=models.CharField(
                default=1,
                max_length=150,
                verbose_name="مشتری از کجا محصول شما رو خریداری کند؟(برای تمام محصولات اعمال میشود)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myshop",
            name="time_end",
            field=models.DateTimeField(
                blank=True,
                default=shop.models.one_month_from_today,
                verbose_name="زمان پایان اشتراک",
            ),
        ),
        migrations.CreateModel(
            name="wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده؟"),
                ),
                (
                    "time_add",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان اضافه شدن"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="نام محصول",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.myshop",
                        verbose_name="نام فروشگاه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوای کامنت")),
                (
                    "date_posted",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="زمان ارسال کامنت",
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="امتیاز",
                    ),
                ),
                ("stars", models.CharField(default=0, max_length=5)),
                ("stars_left", models.CharField(blank=True, max_length=5)),
                (
                    "feedbacker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارسال کننده ی نظر",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, to="shop.Product", verbose_name="کالا"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="myshop",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="shop.Product", verbose_name="محصولات"
            ),
        ),
    ]
