# Generated by Django 3.2.6 on 2021-11-21 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_product_photo_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="last_price",
        ),
    ]
