# Generated by Django 3.2.6 on 2021-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_auto_20211122_1809"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myshop",
            name="link_name",
        ),
        migrations.AlterField(
            model_name="myshop",
            name="head_link",
            field=models.TextField(blank=True, verbose_name="لینک تیتر"),
        ),
    ]
