# Generated by Django 3.2.9 on 2021-12-08 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
