# Generated by Django 3.2.9 on 2021-12-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_wishlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myshop',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='myshop',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='myshop',
            name='head3',
        ),
    ]
