# Generated by Django 3.2.9 on 2021-12-14 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20211212_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='time_add',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان اضافه شدن'),
        ),
    ]
