# Generated by Django 3.2.9 on 2021-12-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_postinfo_time_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="myshop",
            name="about",
            field=models.TextField(default=1, verbose_name="درباره ی فروشگاه"),
            preserve_default=False,
        ),
    ]
