# Generated by Django 3.2.9 on 2021-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0030_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_active",
            field=models.BooleanField(default=False),
        ),
    ]
